# Generated by Django 4.1 on 2022-08-08 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curlutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='original',
            field=models.URLField(validators=[django.core.validators.URLValidator], verbose_name='Оригинальная ссылка'),
        ),
    ]
